name: "Reactive Music: OFF 1.1 (2021-10, 1.18)"
version: "1.1 (2021-10, 1.18)"
author: "D_Greg_D"
description: "I don't understand... Is Reactive Music off? Why do I hear vanilla music?"
credits: "All music is written by C418 (2009-2018), Lena Raine (From 2020), Kumi Tanioka (From 2021), Aaron Cherof (From 2023) and Amos Roddy (From 2025)"

musicSwitchSpeed: LONG
musicDelayLength: LONG

entries:

# Main Menu (music.menu)
- events: [ "main_menu" ]
  forceStopMusicOnChanged: true
  forceStartMusicOnValid: true
  songs:
    # Main Menu soundtrack
    - "mutation" # 2013-11 (1.7.3, 2013 Music Update)
    - "moog_city_2" # 2013-11 (1.7.3, 2013 Music Update)
    - "beginning_2" # 2013-11 (1.7.3, 2013 Music Update)
    - "floating_trees" # 2013-11 (1.7.3, 2013 Music Update)
    # Soundtrack from latest update
    - "infinite_amethyst" # 2021-10 (1.18)
    - "one_more_day" # 2021-10 (1.18)
    - "stand_tall" # 2021-10 (1.18)
    - "wending" # 2021-10 (1.18)

# End Poem (music.credits)
- events: [ "credits" ]
  forceStopMusicOnChanged: true
  forceStartMusicOnValid: true
  songs:
    - "alpha" # 2013-11 (1.7.3, 2013 Music Update)

# Ender Dragon battle (music.dragon)
- events: [ "boss" , "end" ]
  forceStopMusicOnChanged: true
  forceStartMusicOnValid: true
  songs:
    - "boss" # 2013-11 (1.7.3, 2013 Music Update)

# The End (music.end)
- events: [ "end" ]
  songs:
    - "the_end" # 2013-11 (1.7.3, 2013 Music Update)

# Warped Forest (music.nether.warped_forest)
- events: [ "nether", "biome=warped" ]
  forceStopMusicOnChanged: true
  songs:
    - "system_silence"

# Crimson Forest (music.nether.crimson_forest)
- events: [ "nether", "biome=crimson" ]
  songs:
    # The Nether soundtrack
    - "concrete_halls" # 2013-11 (1.7.3, 2013 Music Update)
    - "dead_voxel" # 2013-11 (1.7.3, 2013 Music Update)
    - "warmth" # 2013-11 (1.7.3, 2013 Music Update)
    - "ballad_of_the_cats" # 2013-11 (1.7.3, 2013 Music Update)
    # Crimson Forest soundtrack
    - "chrysopoeia" # 2020-04 (1.16)
    - "chrysopoeia" # 2020-04 (1.16)
    - "chrysopoeia" # 2020-04 (1.16)
    - "chrysopoeia" # 2020-04 (1.16)
    - "chrysopoeia" # 2020-04 (1.16)
    - "chrysopoeia" # 2020-04 (1.16)
    - "chrysopoeia" # 2020-04 (1.16)

# Basalt Deltas and Soul Sand Valley (music.nether.basalt_deltas, music.nether.soul_sand_valley)
- events: [ "nether", "biome=basalt || biome=soul" ]
  songs:
    # The Nether soundtrack
    - "concrete_halls" # 2013-11 (1.7.3, 2013 Music Update)
    - "dead_voxel" # 2013-11 (1.7.3, 2013 Music Update)
    - "warmth" # 2013-11 (1.7.3, 2013 Music Update)
    - "ballad_of_the_cats" # 2013-11 (1.7.3, 2013 Music Update)
    # Basalt Deltas and Soul Sand Valley soundtrack
    - "so_below" # 2020-04 (1.16)
    - "so_below" # 2020-04 (1.16)
    - "so_below" # 2020-04 (1.16)
    - "so_below" # 2020-04 (1.16)
    - "so_below" # 2020-04 (1.16)
    - "so_below" # 2020-04 (1.16)
    - "so_below" # 2020-04 (1.16)

# Nether Wastes (music.nether.nether_wastes)
- events: [ "nether" ]
  forceStopMusicOnChanged: true
  songs:
    # The Nether soundtrack
    - "concrete_halls" # 2013-11 (1.7.3, 2013 Music Update)
    - "dead_voxel" # 2013-11 (1.7.3, 2013 Music Update)
    - "warmth" # 2013-11 (1.7.3, 2013 Music Update)
    - "ballad_of_the_cats" # 2013-11 (1.7.3, 2013 Music Update)
    # Nether Wastes soundtrack
    - "rubedo" # 2020-04 (1.16)
    - "rubedo" # 2020-04 (1.16)
    - "rubedo" # 2020-04 (1.16)
    - "rubedo" # 2020-04 (1.16)
    - "rubedo" # 2020-04 (1.16)
    - "rubedo" # 2020-04 (1.16)

# Underwater (music.overworld.under_water)
- events: [ "underwater", "biome=river || biometag=river || biome=ocean || biometag=ocean" ]
  songs:
    - "axolotl" # 2018-06 (1.13)
    - "dragon_fish" # 2018-06 (1.13)
    - "shuniji" # 2018-06 (1.13)

# Lush Caves (music.overworld.lush_caves)
- events: [ "biometag=underground", "biome=lush || biome=jungle" ]
  songs:
    # General soundtrack
    - "clark" # 2009-06 (Classic 0.0.22a)
    - "clark" # 2009-06 (Classic 0.0.22a)
    - "floating_dream" # 2021-10 (1.18)
    - "floating_dream" # 2021-10 (1.18)
    - "left_to_bloom" # 2021-10 (1.18)
    - "left_to_bloom" # 2021-10 (1.18)
    - "left_to_bloom" # 2021-10 (1.18)
    - "left_to_bloom" # 2021-10 (1.18)
    - "mice_on_venus" # 2010-07 (Alpha 1.0.14)
    - "mice_on_venus" # 2010-07 (Alpha 1.0.14)
    - "minecraft" # 2009-06 (Classic 0.0.22a)
    - "minecraft" # 2009-06 (Classic 0.0.22a)
    - "one_more_day" # 2021-10 (1.18)
    - "one_more_day" # 2021-10 (1.18)
    - "sweden" # 2009-06 (Classic 0.0.22a)
    - "sweden" # 2009-06 (Classic 0.0.22a)
    # Non-general soundtrack
    - "an_ordinary_day" # 2021-10 (1.18)
    - "an_ordinary_day" # 2021-10 (1.18)

# Dripstone Caves (music.overworld.dripstone_caves)
- events: [ "biometag=underground" ]
  songs:
    # General soundtrack
    - "danny" # 2010-10 (Alpha 1.2.0)
    - "key" # 2010-10 (Alpha 1.2.0)
    - "oxygene" # 2010-10 (Alpha 1.2.0)
    - "subwoofer_lullaby" # 2010-10 (Alpha 1.2.0)
    # Non-general soundtrack
    - "an_ordinary_day" # 2021-10 (1.18)
    - "infinite_amethyst" # 2021-10 (1.18)
    - "wending" # 2021-10 (1.18)
    - "wending" # 2021-10 (1.18)

# Jagged Peaks (music.overworld.jagged_peaks)
- events: [ "biome=jagged_peaks" ]
  songs:
    # General soundtrack
    - "floating_dream" # 2021-10 (1.18)
    - "dry_hands" # 2010-07 (Alpha 1.0.14)
    - "key" # 2010-10 (Alpha 1.2.0)
    - "living_mice" # 2010-10 (Alpha 1.2.0)
    - "mice_on_venus" # 2010-07 (Alpha 1.0.14)
    - "oxygene" # 2010-10 (Alpha 1.2.0)
    - "subwoofer_lullaby" # 2010-10 (Alpha 1.2.0)
    - "wet_hands" # 2010-07 (Alpha 1.0.14)
    # Non-general soundtrack
    - "stand_tall" # 2021-10 (1.18)
    - "wending" # 2021-10 (1.18)

# Stony Peaks (music.overworld.stony_peaks)
- events: [ "biome=stony_peaks" ]
  songs:
    # General soundtrack
    - "danny" # 2010-10 (Alpha 1.2.0)
    - "dry_hands" # 2010-07 (Alpha 1.0.14)
    - "haggstrom" # 2010-10 (Alpha 1.2.0)
    - "living_mice" # 2010-10 (Alpha 1.2.0)
    - "mice_on_venus" # 2010-07 (Alpha 1.0.14)
    - "subwoofer_lullaby" # 2010-10 (Alpha 1.2.0)
    - "wet_hands" # 2010-07 (Alpha 1.0.14)
    # Non-general soundtrack
    - "stand_tall" # 2021-10 (1.18)
    - "stand_tall" # 2021-10 (1.18) (maybe only one, information on Minecraft Wiki is different)
    - "wending" # 2021-10 (1.18)

# Frozen Peaks (music.overworld.frozen_peaks)
- events: [ "biome=frozen_peaks || biometag=mountain_peak" ]
  songs:
    # General soundtrack
    - "danny" # 2010-10 (Alpha 1.2.0)
    - "dry_hands" # 2010-07 (Alpha 1.0.14)
    - "haggstrom" # 2010-10 (Alpha 1.2.0)
    - "living_mice" # 2010-10 (Alpha 1.2.0)
    - "mice_on_venus" # 2010-07 (Alpha 1.0.14)
    - "subwoofer_lullaby" # 2010-10 (Alpha 1.2.0)
    - "wet_hands" # 2010-07 (Alpha 1.0.14)
    # Non-general soundtrack
    - "stand_tall" # 2021-10 (1.18)
    - "stand_tall" # 2021-10 (1.18)

# Meadow (music.overworld.meadow)
- events: [ "biome=meadow" ]
  songs:
    # General soundtrack
    - "danny" # 2010-10 (Alpha 1.2.0)
    - "haggstrom" # 2010-10 (Alpha 1.2.0)
    - "left_to_bloom" # 2021-10 (1.18)
    - "living_mice" # 2010-10 (Alpha 1.2.0)
    - "one_more_day" # 2021-10 (1.18)
    - "one_more_day" # 2021-10 (1.18)
    - "subwoofer_lullaby" # 2010-10 (Alpha 1.2.0)

# Grove (music.overworld.grove)
- events: [ "biome=grove || biometag=mountain_slope", "biome=grove || biometag=forest" ]
  songs:
    # General soundtrack
    - "clark" # 2009-06 (Classic 0.0.22a)
    - "comforting_memories" # 2021-10 (1.18)
    - "key" # 2010-10 (Alpha 1.2.0)
    - "mice_on_venus" # 2010-07 (Alpha 1.0.14)
    - "oxygene" # 2010-10 (Alpha 1.2.0)
    - "minecraft" # 2009-06 (Classic 0.0.22a)
    - "sweden" # 2009-06 (Classic 0.0.22a)
    # Non-general soundtrack
    - "infinite_amethyst" # 2021-10 (1.18)
    - "wending" # 2021-10 (1.18)

# Snowy Slopes (music.overworld.snowy_slopes)
- events: [ "biome=slope || biometag=mountain_slope" ]
  songs:
    # General soundtrack
    - "haggstrom" # 2010-10 (Alpha 1.2.0)
    - "living_mice" # 2010-10 (Alpha 1.2.0)
    - "one_more_day" # 2021-10 (1.18)
    - "subwoofer_lullaby" # 2010-10 (Alpha 1.2.0)
    # Non-general soundtrack
    - "an_ordinary_day" # 2021-10 (1.18)
    - "stand_tall" # 2021-10 (1.18)

# Other biomes (music.game)
- events: [ "overworld" ]
  songs:
    # General soundtrack
    - "clark" # 2009-06 (Classic 0.0.22a)
    - "comforting_memories" # 2021-10 (1.18)
    - "danny" # 2010-10 (Alpha 1.2.0)
    - "dry_hands" # 2010-07 (Alpha 1.0.14)
    - "haggstrom" # 2010-10 (Alpha 1.2.0)
    - "floating_dream" # 2021-10 (1.18)
    - "key" # 2010-10 (Alpha 1.2.0)
    - "left_to_bloom" # 2021-10 (1.18)
    - "living_mice" # 2010-10 (Alpha 1.2.0)
    - "mice_on_venus" # 2010-07 (Alpha 1.0.14)
    - "minecraft" # 2009-06 (Classic 0.0.22a)
    - "one_more_day" # 2021-10 (1.18)
    - "oxygene" # 2010-10 (Alpha 1.2.0)
    - "subwoofer_lullaby" # 2010-10 (Alpha 1.2.0)
    - "sweden" # 2009-06 (Classic 0.0.22a)
    - "wet_hands" # 2010-07 (Alpha 1.0.14)
