
["Jetpack Height Restriction"]
	brassJetpackMaxHeight = 28.0
	andesiteJetpackMaxHeight = 18.0
	copperJetpackMaxHeight = 18.0
	netheriteJetpackMaxHeight = 32.0
	enableAboveCloudEnchant = false

["Jetpack/Grapplin Speed"]
	brassJetpackSpeed = 0.035
	andesiteJetpackSpeed = 0.03
	copperJetpackSpeed = 0.015
	netheriteJetpackSpeed = 0.04
	grapplinWhiskSpeed = 0.1

["Fuel/Water Capacity"]
	gadgetCapacity = 1600.0
	smallTankCapacity = 800.0
	mediumTankCapacity = 1600.0
	largeTankCapacity = 3200.0

[Enchantments]
	enableDiggingEnchant = true
	enableImpactEnchant = true
	enableGravityGunEnchant = true
	enableHellfireEnchant = true

["Drone Module"]
	enableDrillDroneModule = false
	enableFanDroneModule = true
	enableMagnetDroneModule = false
	enableVaultDroneModule = true
	MagnetModuleBlockLimitation = false

